repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        # args: ["-L", "sur,nd"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        files: src
        args: ["--install-types", "--non-interactive"]

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.5.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/tox-dev/tox-toml-fmt
    rev: v1.0.0
    hooks:
      - id: tox-toml-fmt
